name: ubuntu-latest test
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
    paths:
      - '**.cpp'
      - '**.h'
    tags:
      - '*'
jobs:
  ubuntutest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup system for non-MPI tests
        run: |
          sudo sh -c 'echo -1 >/proc/sys/kernel/perf_event_paranoid'
          sudo apt update
          sudo apt install build-essential python3-dev \
                           papi-tools libpapi-dev \
                           libhdf5-dev hdf5-tools
      - name: Build+Test for non-MPI
        run: |
          cd test
          ./test.sh
          cd ..
      - name: Setup system for MPI tests
        run: |
          sudo apt purge libhdf5-dev hdf5-tools
          sudo apt install mpi-default-dev python3-mpi4py \
                           libhdf5-mpi-dev hdf5-tools
      - name: Build+Test for MPI
        run: |
          HDF5_ROOT=/usr/lib/x86_64-linux-gnu/hdf5/openmpi
          export HDF5_ROOT
          cd test
          ./test.sh
          cd ..
